app/conf/urls.py
urlpatterns += patterns('',
    url(r"^", include("phphost.urls")),
)

ext/urls.py
for file_name in sorted(os.listdir(normpath(PROJECT_ROOT, "ext"))):
    if "_" in file_name and not "__" in file_name:
        execfile(normpath(PROJECT_ROOT, "ext", file_name, "conf/urls.py"))

sdv/conf/urls.py
if DEBUG:
    urlpatterns += patterns('',
        url(r'^static/uploads/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': MEDIA_ROOT,
        }), 
        url(r'^static/static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': STATIC_ROOT,
        }), 
   ) 

if ADMIN_URLS:
    from django.contrib import admin

    admin.autodiscover()
    urlpatterns += patterns('', 
        url(r'^admin/', include(admin.site.urls)),
    )

srv/urls.py
from settings import *

from django.conf.urls import patterns, include, url

urlpatterns = patterns('')

execfile(normpath(PROJECT_ROOT, "sdv/conf/urls.py"))
execfile(normpath(PROJECT_ROOT, "ext/urls.py"))
execfile(normpath(PROJECT_ROOT, "app/conf/urls.py"))

app/local_apps/phphost/models.py
# coding=utf-8

from django.db import models
from django.contrib.auth.models import User

import datetime

import libssm

HOSTING_TYPES = (
    ("basic", "Basic (299Kč/rok)"),
    ("standard", "Standard (399Kč/rok)"),
    ("pro", "Pro (499Kč/rok)"),
    ("unlimit", "Unlimit (899Kč/rok)"),
)

class UserProfile(User):
    pass

class Hosting(models.Model):
    owner = models.ForeignKey(UserProfile)

    domain = models.CharField(max_length=255, unique=True)
    hosting_type = models.CharField(max_length=32, choices=HOSTING_TYPES)
    created_at = models.DateField(auto_now_add=True)
    last_payment = models.DateField(auto_now_add=True)

    def get_ssmdomain(self):
        return libssm.Domain(self.domain)

    def get_ftp_server(self):
        return "ftp.%s" % self.domain

    def get_ftp_user(self):
        return self.get_ssmdomain().user

    def get_mysql_server(self):
        return "localhost"

    def get_mysql_user(self):
        return self.get_ssmdomain().mysql_user

    def get_expire_date(self):
        return self.last_payment + datetime.timedelta(days=364)

    def __unicode__(self):
        return u"%s" % self.domain

app/local_apps/phphost/forms.py
from django import forms

from models import Hosting


class HostingForm(forms.ModelForm):
    class Meta:
        model = Hosting
        fields = ["domain", "hosting_type"]

app/local_apps/phphost/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

from models import UserProfile, Hosting
from forms import HostingForm

from api import set_ftp_passwd, set_mysql_passwd, add_hosting

@login_required
def dashboard_home_view(request, template="phphost/dashboard/home.html"):
    return render_to_response(template,
        {},
        context_instance=RequestContext(request))

@login_required
def dashboard_hosting_view(request, domain, template="phphost/dashboard/hosting.html"):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: alert = request.GET["alert"]
    except KeyError: alert = ""
    return render_to_response(template,
        {"hosting": hosting, "alert": alert},
        context_instance=RequestContext(request))

def dashboard_hosting_add_view(request, template="phphost/dashboard/add_hosting.html"):
    form = HostingForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.owner = request.user.userprofile
        obj.save()
        add_hosting(obj.domain)
        return HttpResponseRedirect((reverse("phphost.dashboard.hosting", args=[obj.domain, ])))
    return render_to_response(template,
        {"form": form},
        context_instance=RequestContext(request))

@login_required
def set_ftp_passwd_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: passwd = request.POST["passwd"]
    except KeyError: passwd = None
    if passwd:
        set_ftp_passwd(hosting.domain, passwd)
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ])+"?alert=success")

@login_required
def set_mysql_passwd_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: passwd = request.POST["passwd"]
    except KeyError: passwd = None
    if passwd:
        set_mysql_passwd(hosting.domain, passwd)
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ])+"?alert=success")

app/local_apps/phphost/templates/phphost/dashboard/add_hosting.html
{% extends "phphost/base.html" %}
{% block content %}
<div class="row-fluid">
            <div class="span12">
    {% if alert == "success" %}
    <div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  Změna byla úspěšně provedena.
</div>
{%endif%}
              <h2>Přidat hosting</h2>
              <form action="" method="post">
              {% csrf_token %}  
              {{form.as_p}}
              <input type="submit" value="přidat">
              </form>
            </div><!--/span-->
            </div><!--/span-->
{% endblock content %}

app/local_apps/phphost/templates/phphost/dashboard/home.html
{% extends "phphost/base.html" %}
{% block content %}
<h2>Administrace PHPhost</h2>
<p>Domény musí směřovat na IP <strong>37.157.193.237</strong>. Proto nastavte A záznam na tuto IP. Dále je třeba nacílit všechny subdomény <strong>*</strong> pomocí CNAME na <strong>vasedomana.cz</strong>.</p>
{% endblock content %}

app/local_apps/phphost/templates/phphost/dashboard/hosting.html
{% extends "phphost/base.html" %}
{% block content %}
<div class="row-fluid">
            <div class="span12">
    {% if alert == "success" %}
    <div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  Změna byla úspěšně provedena.
</div>
{%endif%}
              <h2>Doména {{hosting.domain}}</h2>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">
            <div class="span4">
              <h3>Info</h3>
              <table class="table">
                <tr>
                    <th>expirace</th>
                    <td>{{hosting.get_expire_date}}</td>
                </tr>
                <tr>
                    <th>hosting</th>
                    <td>{{hosting.get_hosting_type_display}}</td>
                </tr>
                <tr>
                    <th></th>
                    <td><a href="http://{{hosting.domain}}" target="blank">{{hosting.domain}}</a></td>
                </tr>
                <tr>
                    <th></th>
                    <td><a href="http://mysql.h4y.cz" target="blank">phpMyAdmin</a></td>
                </tr>
              </table>
            </div><!--/span-->
            <div class="span4">
              <h3>FTP</h3>
              <table class="table">
                <tr>
                    <th>jméno</th>
                    <td>{{hosting.get_ftp_user}}</td>
                </tr>
                <tr>
                    <th>server</th>
                    <td>{{hosting.get_ftp_server}}</td>
                </tr>
                <tr>
                    <th>heslo</th>
                    <td><form action="{%url phphost.dashboard.hosting.set_ftp_passwd hosting.domain %}" method="post">{% csrf_token %}<input type="text" name="passwd" style="width:120px;margin:0;"> <input type="submit" value="nastavit"></form></td>
                </tr>
              </table>
            </div><!--/span-->
            <div class="span4">
              <h3>MySQL</h3>
              <table class="table">
                <tr>
                    <th>jméno</th>
                    <td>{{hosting.get_mysql_user}}</td>
                </tr>
                <tr>
                    <th>server</th>
                    <td>{{hosting.get_mysql_server}}</td>
                </tr>
                <tr>
                    <th>heslo</th>
                    <td><form action="{%url phphost.dashboard.hosting.set_mysql_passwd hosting.domain %}" method="post">{% csrf_token %}<input type="text" name="passwd" style="width:120px;margin:0;"> <input type="submit" value="nastavit"></form></td>
                </tr>
              </table>
            </div><!--/span-->
          </div><!--/row-->
{% endblock content %}