app/conf/urls.py
urlpatterns += patterns('',
    url(r"^", include("phphost.urls")),
)

ext/urls.py
for file_name in sorted(os.listdir(normpath(PROJECT_ROOT, "ext"))):
    if "_" in file_name and not "__" in file_name:
        execfile(normpath(PROJECT_ROOT, "ext", file_name, "conf/urls.py"))

sdv/conf/urls.py
if DEBUG:
    urlpatterns += patterns('',
        url(r'^static/uploads/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': MEDIA_ROOT,
        }), 
        url(r'^static/static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': STATIC_ROOT,
        }), 
   ) 

if ADMIN_URLS:
    from django.contrib import admin

    admin.autodiscover()
    urlpatterns += patterns('', 
        url(r'^admin/', include(admin.site.urls)),
    )

srv/urls.py
from settings import *

from django.conf.urls import patterns, include, url

urlpatterns = patterns('')

execfile(normpath(PROJECT_ROOT, "sdv/conf/urls.py"))
execfile(normpath(PROJECT_ROOT, "ext/urls.py"))
execfile(normpath(PROJECT_ROOT, "app/conf/urls.py"))

app/local_apps/phphost/models.py
# coding=utf-8

from django.db import models
from django.contrib.auth.models import User

import datetime

import libssm

HOSTING_TYPES = (
    ("basic", "Basic (299Kč/rok)"),
    ("standard", "Standard (399Kč/rok)"),
    ("pro", "Pro (499Kč/rok)"),
    ("unlimit", "Unlimit (899Kč/rok)"),
)

class UserProfile(User):
    pass

class Hosting(models.Model):
    owner = models.ForeignKey(UserProfile)

    domain = models.CharField(max_length=255, unique=True)
    hosting_type = models.CharField(max_length=32, choices=HOSTING_TYPES)
    created_at = models.DateField(auto_now_add=True)
    last_payment = models.DateField(auto_now_add=True)

    def get_ssmdomain(self):
        return libssm.Domain(self.domain)

    def get_ftp_server(self):
        return "ftp.%s" % self.domain

    def get_ftp_user(self):
        return self.get_ssmdomain().user

    def get_mysql_server(self):
        return "localhost"

    def get_mysql_user(self):
        return self.get_ssmdomain().mysql_user

    def get_expire_date(self):
        return self.last_payment + datetime.timedelta(days=364)

    def __unicode__(self):
        return u"%s" % self.domain

app/local_apps/phphost/forms.py
from django import forms

from models import Hosting


class HostingForm(forms.ModelForm):
    class Meta:
        model = Hosting
        fields = ["domain", "hosting_type"]

app/local_apps/phphost/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

from models import UserProfile, Hosting
from forms import HostingForm

from api import set_ftp_passwd, set_mysql_passwd, add_hosting

@login_required
def dashboard_home_view(request, template="phphost/dashboard/home.html"):
    return render_to_response(template,
        {},
        context_instance=RequestContext(request))

@login_required
def dashboard_hosting_view(request, domain, template="phphost/dashboard/hosting.html"):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: alert = request.GET["alert"]
    except KeyError: alert = ""
    return render_to_response(template,
        {"hosting": hosting, "alert": alert},
        context_instance=RequestContext(request))

def dashboard_hosting_add_view(request, template="phphost/dashboard/add_hosting.html"):
    form = HostingForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.owner = request.user.userprofile
        obj.save()
        add_hosting(obj.domain)
        return HttpResponseRedirect((reverse("phphost.dashboard.hosting", args=[obj.domain, ])))
    return render_to_response(template,
        {"form": form},
        context_instance=RequestContext(request))

@login_required
def set_ftp_passwd_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: passwd = request.POST["passwd"]
    except KeyError: passwd = None
    if passwd:
        set_ftp_passwd(hosting.domain, passwd)
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ])+"?alert=success")

@login_required
def set_mysql_passwd_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: passwd = request.POST["passwd"]
    except KeyError: passwd = None
    if passwd:
        set_mysql_passwd(hosting.domain, passwd)
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ])+"?alert=success")

app/local_apps/phphost/templates/phphost/base.html
{% extends "base.html" %}
{%block body%}
    <!-- START PAGE -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">PHPhost.cz</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <strong>{{request.user.userprofile.get_full_name}} ({{request.user.userprofile.username}})</strong>
            </p>
            <ul class="nav">
              <li><a href="{% url phphost.dashboard.home %}">Home</a></li>
              <li><a href="{% url phphost.dashboard.hosting.add %}" >Přidat hosting</a></li>
              <li><a href="/accounts/logout/" class="navbar-link">odhlásit se</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid" id="container">
      {% block base_content %}
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Domény</li>
              {% for obj in request.user.userprofile.hosting_set.all %}
              <li><!--  class="active" --><a href="{% url phphost.dashboard.hosting obj.domain %}">{{obj.domain}}</a></li>
              {%endfor%}
            </ul>
          </div><!--/.well -->
<iframe scrolling="no" style="border: 0; width: 200px; height: 200px;" src="http://coinurl.com/get.php?id=18404"></iframe>
<iframe scrolling="no" style="border: 0; width: 200px; height: 200px;" src="http://coinurl.com/get.php?id=18404"></iframe>
        </div><!--/span-->
        <div class="span9">
          {% block content %}
        
          {% endblock content %}
<iframe scrolling="no" style="border: 0; width: 728px; height: 90px;" src="http://coinurl.com/get.php?id=18403"></iframe>
<iframe scrolling="no" style="border: 0; width: 728px; height: 90px;" src="http://coinurl.com/get.php?id=18403"></iframe>
        </div><!--/span-->
      </div><!--/row-->
      {% endblock base_content %}
      <hr>

      <footer>
        <p>2012 &copy; PHPhost.cz | Vytvořil &amp; provozuje <a href="http://ondrejsika.com">Ondřej Šika</a></p>
      </footer>

    </div><!--/.fluid-container-->

    {%endblock body%}

app/local_apps/phphost/templates/phphost/index.html
<a href="/dashboard">Administrace</a>

<hr>

<code><pre>
# PHPhost.cz 2.0

Mate zajem o pristup do bety? Vyplnte <a target="blank" href="https://docs.google.com/forms/d/1VfrixZzPCgAAh_ZGy67v-ymX0QyT-JCl_xD8fC4vOsQ/viewform?usp=send_form">formular</a>

Pokud se chcete zapojit do vyvoje nebo jinak spolupracovat? Vyplnte <a target="blank" href="https://docs.google.com/forms/d/1pL6Tf_tenf3RSWM8iZmoh5Mmv0MSABy9jO6524z26zo/viewform?usp=send_form">formular</a>

Muzete take prispet na vyvoj hostingu na ucet <b>2500171198/2010</b> (Ondrej Sika, Fio Banka) a nebo na adresu <b>1JN3LoHYkdThYFpLpcyVTw3GQDkMGGhMuD</b>


## Web hosting clasic (100 Kc / mesic)

* neomezene domen, subdomen
* neomezeny pocet databazi
* ftp, sftp, git
* https (vlastni certifikat, sdileny certifikat (nase domena), self-sign certifikat)
* php, apache
* mysql, postgresql
* 50 GB data
* 5 GB databaze
* cron (5 min)
* smtp server (odesilani emailu)
* predinstalace wordpresu, prestashopu, magenta, ...


## Web hosting extra (150 Kc / mesic)

Stejne jako webhosting clasic

* 100 GB data
* 15 GB databaze
* DNS server
* cron (1 min)
* monitoring


## Email hosting clasic (100 Kc / mesic)

* neomezene domen
* neomezene uctu
* 5 GB (nebo 15 GB za 200 Kc)
* sleva 30% pri koupi webhostingu
* smpt, pop, imap
* web client roundcube.net, mailpie.is, rainloop.net


## Ostatni

* bitcoin platby (sleva 10%)
* email podpora 24/7
* high security - two factor auth (OTP, PGP)


## Kontakt

* <a href="mailto:info@phphost.cz">info@phphost.cz</a>


</pre></code>